# Generated by Django 4.0.4 on 2022-05-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
